# -*- coding: utf-8 -*-
"""Untitled9.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1oH3tTTq3vXZ1FOEuxLAIu-JyuNMywvCJ
"""

def generar_matriz(filas, columnas):
    matriz=[]
    for i in range(filas):
        fila=[0] * columnas
        matriz.append(fila)
    return matriz

def mostrar_matriz(matriz):

    # Mostrar encabezado con los números de día
    print("   ", end="")
    for j in range(1, len(matriz[0])+1):
        print(f"  {j}", end="")
    print()
    
    i=-1
    for fila in matriz:
        i+=1
        print(f"F {i}",fila)
    

def ingresar_datos(matriz):
    for i in range(len(matriz)):
      for j in range(len(matriz[0])):
          toneladas=int(input(f"ingrese toneladas producidas para la faena {i+1}en el dia {j+1}: "))
          matriz[i][j]=int(toneladas)

def calcular_produccion_faena(matriz, faena):
    total = sum(matriz[faena])
    return total

def calcular_produccion_dia(matriz,dia):
    total = sum([fila[dia]for fila in matriz])
    return total

def main():
    faenas = int(input("ingrese el numero de faenas: "))
    dias = int(input("ingrese el numero de dias de  produccion:"))
    matriz = generar_matriz(faenas, dias)
    menu = True

    while menu == True:
      print("\n---MENU---")
      print("1. generar plan de produccion")
      print("2. ingresar datos de produccion")
      print("3. calcular la produccion total de una faena especifica")
      print("4. calcular produccion total de todas las faenas en un dia especifico")
      print("5. salir del programa")

      opcion = int(input("\nSeleccione una opcion: "))

      if opcion == 1:
        print("\nPlan de produccion:")
        mostrar_matriz(matriz)

      elif opcion == 2:
        ingresar_datos(matriz)

      elif opcion == 3:
        faena = int(input("ingrese el numero de la faena a calcular: "))
        produccion_faena = calcular_produccion_faena(matriz, faena)
        print(f"la produccion total de la faena {faena} es: {produccion_faena}")

      elif opcion == 4:
        dia = int(input("ingrese el numero del dia a calcular: "))
        produccion_dia = calcular_produccion_dia(matriz, dia)
        print(f"la produccion total de todas las faenas el dia {dia} es: {produccion_dia}")

      elif opcion == 5:
        menu = False 
        print("\n¡Hasta luego!")
      else:
        print("\nOpcion invalida. intente de nuevo")

if __name__ == "__main__":
   main()
